### ISSUE TITLE
Selection option background

### ISSUE THREAD

**Issue by StopNGo** [rezonmain/nertu#1] opened 2022-10-01 23:51 UTC
Hi!

Chrome 105.0.5195.127, 64-bit, Windows 10

I think, you need to change your selection option background from inherit -> transparent to forced black or whatever else dark.

![P05mAs](https://user-images.githubusercontent.com/7091805/193432194-c40be9ca-28c5-4fa2-91bf-45a546e4bf60.png)

I can create a Pull Request, if you want.

**Comment by rezonmain** [comment] 2022-10-02 00:15
I like using native HTML input elements when I can, but oh god they're a pain to style consistently across browsers. I'll push an update to fix it.

**Comment by rezonmain** [comment] 2022-10-02 00:58
With commit 3f858b29b0196336d7c2d30e481a799f97b38bfb the styling should be more consistent with the theme, I don't have the hardware to reproduce the issue but tested with BrowserStack and It seemed fixed.

Here is a link to the live commit: https://nertu-pnjx6dq9l-rezonmain.vercel.app/, (it may need a refresh due to the service worker caching the files). If you can confirm I'll close the issue and merge to main.

**Closed as completed** 2022-10-02 03:45 UTC

**Comment by StopNGo** [comment] 2022-10-02 18:32
Everything is ok now. Thanks!
